version: "3.3"
services:
  db:
    container_name: db
    image: postgres:11.13
    environment:
      - POSTGRES_USER=pfile
      - POSTGRES_PASSWORD=pfile
      - POSTGRES_DB=pfile
      - TZ=Europe/Moscow
      - PGTZ=Europe/Moscow
#    ports:
#      - "5432:5432" # todo [remove]
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/scripts:/docker-entrypoint-initdb.d
    networks:
      - transcendence
  nest:
    container_name: nest-connector
    build:
      context: nest-connector
    ports:
      - "3000:3000"
    environment:
      - TZ=Europe/Moscow
      - DB_HOST=db
      - POSTGRES_USER=pfile
      - POSTGRES_PASSWORD=pfile
      - POSTGRES_DB=pfile
    networks:
      transcendence:
        ipv4_address: 172.20.0.5
    depends_on:
      - db
  web:
    container_name: web
    build: ./web
    ports:
      - "8080:3000"
    networks:
      - transcendence
networks:
  transcendence:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
