version: "3.3"
services:
  db:
    container_name: db
    image: postgres:11.13
    environment:
      - POSTGRES_USER=pfile
      - POSTGRES_PASSWORD=pfile
      - POSTGRES_DB=pfile
      - TZ=Europe/Moscow
      - PGTZ=Europe/Moscow
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/scripts:/docker-entrypoint-initdb.d
    networks:
      - transcendence
    command: postgres -c stats_temp_directory=/tmp
  nest:
    container_name: nest-connector
    build:
      context: nest-connector
    ports:
      - "3000:3000"
    volumes:
      - ./nest-connector/uploads:/uploads
    environment:
      - API_URL=http://localhost:3000
      - TZ=Europe/Moscow
      - DB_HOST=db
      - POSTGRES_USER=pfile
      - POSTGRES_PASSWORD=pfile
      - POSTGRES_DB=pfile
      - JWT_SECRET=4f0dbc852c89e3310b5acd7b5adcef4d49adanio125husb9zsabq1873b18vcas
      - INTRA_UID=17bb7c5a7145cc62b5fb4e37613f83dde638ca6ed7e92128205c20dd3b2652da
      - INTRA_SECRET=81ea8afb3ffaa09ea6b38f3b56b598cd9c04d41944838024fbfbbb6fd1b4c820
      - INTRA_REDIRECT=http://localhost:8080/login
      - TWILIO_ACCOUNT_SID=AC_TODO
      - TWILIO_AUTH_TOKEN=TODO
      - TWILIO_SERVICE_SID=TODO
    networks:
      transcendence:
        ipv4_address: 172.20.0.5
    depends_on:
      - db
  web:
    container_name: web
    build: ./web
    ports:
      - "8080:3000"
    networks:
      - transcendence
networks:
  transcendence:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
