version: "3.3"
services:
  sql:
    container_name: sql
    build:
      context: PostgreSQL
    ports:
      - "5432:5432"
    # volumes:
    # - ./PostgreSQL/data:/var/lib/postgresql/11/main
    networks:
      - transcendence
    # command: /start.sh
  nest:
    container_name: nest-connector
    command: bash -c "npm install && npm run start:dev"
    build:
      context: nest-connector
    ports:
      - "3000:3000"
    # Dev
    volumes:
      - ./nest-connector/app:/transcendence
    networks:
      transcendence:
        ipv4_address: 172.20.0.5
  web:
    container_name: web
    build: ./web
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    ports:
      - "8080:3000"
    networks:
      - transcendence
networks:
  transcendence:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
