version: "3.3"
services:
  sql:
    container_name: sql
    build: ./PostgreSQL/
    ports:
    - "5432:5432"
    # volumes:
    #   - ./PostgreSQL/data:/var/lib/postgresql/11/main
    networks:
      - transcendence
  nest:
    container_name: nest-connector
    # command: npm run start:dev
    build:
      context: nest-connector
    ports:
      - "3000:3000"
    volumes:
      - ./nest-connector/app:/transcendence
    networks:
      transcendence:
        ipv4_address: 172.20.0.5
  # web:
  #   container_name: web
  #   build: ./web
  #   ports:
  #     - "8080:8080"
networks:
  transcendence:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
